MAP-72-Refactor-skip-link
ministryofjustice/hmpps-welcome-people-into-prison-ui pull request #424
Opened 2023-08-14 16:45 UTC by davidthomas22

2023-08-14 16:53 UTC, davidthomas22 commented on server/views/pages/home.njk
added `skipLink` block to override `main` block behaviour and ensure that the skip link takes you to the homepage content

2023-08-14 16:55 UTC, davidthomas22 commented on server/views/partials/layout.njk
> +{% block skipLink %}
Added to layout partial to ensure skip link underline is enforced on page

2023-08-14 16:56 UTC, davidthomas22 commented on server/views/pages/home.njk
> +{% block skipLink %}
added `skipLink` block to override `main` block behaviour and ensure that the skip link takes you to the homepage content

2023-08-15 06:40 UTC, GurnankCheema approved these changes
LGTM

2023-08-15 07:20 UTC, GurnankCheema requested changes
Code for skip link all okay but there's a small blip in the layout as grey footer now extends to  top of main content. probably just a missing div etc - now resolved

2023-08-15 08:16 UTC, GurnankCheema approved these changes
LGTM

2023-08-15 08:25 UTC, merged